---
- name: Pre-scaleup checks
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - fail:
      msg: >
        Detected no new_workers in inventory. Please add hosts to the
        new_workers host group to add nodes.
    when: groups.new_workers | default([]) | length == 0

- name: install nodes
  hosts: new_workers
  roles:
  - openshift_node
