---
baseDomain: example.com
machines:
- name: master
  replicas: 1
- name: worker
  # This should always be zero for openshift-ansible
  replicas: 0
metadata:
  name: mycluster
networking:
  clusterNetworks:
  - cidr: 10.128.0.0/14
    hostSubnetLength: 9
  serviceCIDR: 172.30.0.0/16
  type: OpenShiftSDN
platform:
  libvirt:
    # This URI is not actually used
    URI: null
    defaultMachinePlatform:
      image: file:///unused
    masterIPs: null
    network:
      if: null
      ipRange: null
pullSecret: |
  < paste your pullSecret here >
sshKey: |
  < paster your pubkey here >
