---
- name: Set cloud provider facts
  openshift_facts:
    role: cloudprovider
    system_facts: "{{ vars_openshift_facts_system_facts }}"
    local_facts:
      kind: "{{ openshift_cloudprovider_kind | default(None) }}"

- name: Create cloudprovider config dir
  file:
    path: "{{ openshift.common.config_base }}/cloudprovider"
    state: directory

- name: include the defined cloud provider files
  include_tasks: "{{ openshift_cloudprovider_kind }}.yml"
