---
- name: Install iSCSI storage plugin dependencies
  package:
    name: "{{ pkg_list | join(',') }}"
    state: present
  when: not openshift_is_atomic | bool
  register: result
  until: result is succeeded
  vars:
    pkg_list:
      - iscsi-initiator-utils
      - device-mapper-multipath

- name: restart services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: True
  when: not openshift_is_atomic | bool
  with_items:
    - multipathd
    - rpcbind
    - iscsid

# Copy the conf file only if not exists
- name: Template multipath configuration
  template:
    dest: "/etc/multipath.conf"
    src: multipath.conf.j2
    backup: true
    force: no
  when: not openshift_is_atomic | bool

# If the conf file already exists, update it
- name: "Add LIO-ORG in MultiPath configuration"
  blockinfile:
    path: /etc/multipath.conf
    marker: "# <!-- {mark} ANSIBLE MANAGED BLOCK -->"
    block: |
      devices {
          device {
                    vendor "LIO-ORG"
                    product "TCMU device"
                    user_friendly_names "yes"
                    path_grouping_policy "failover"
                    path_selector "round-robin 0"
                    failback immediate
                    path_checker "tur"
                    prio "alua"
                    hardware_handler "1 alua"
                    no_path_retry 120
                    rr_weight "uniform"
          }
      }
    owner: root
    group: root
    mode: 0600
    backup: yes
    state: present

#enable multipath
- name: Enable and start multipath
  command: "mpathconf --enable --with_multipathd y"
  when: not openshift_is_atomic | bool
