---
- name: Install openshift support packages
  package:
    name: "{{ openshift_node_support_packages | join(',') }}"
    update_cache: true
  async: 3600
  poll: 30

# FIXME: Creation of these directories should not be required for crio 1.14.5
- name: Create CNI dirs for crio
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - /var/lib/cni/bin
    - /etc/kubernetes/cni/net.d/
    - /opt/cni/bin/

- name: Install openshift packages
  package:
    name: "{{ openshift_node_packages | join(',') }}"
    state: "{{ openshift_node_package_state }}"
  async: 3600
  poll: 30

- name: Enable the CRI-O service
  systemd:
    name: "cri-o"
    enabled: yes
