---
- name: Pre-upgrade checks
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Ensure [workers] group is populated
    fail:
      msg: >
        Detected no workers in inventory. Please add hosts to the
        workers host group to upgrade nodes
    when: groups.workers | default([]) | length == 0

- name: upgrade nodes
  hosts: workers
  serial: 1
  tasks:
  - import_role:
      name: openshift_node
      tasks_from: upgrade.yml
